DROP TABLE IF EXISTS user;
DROP TABLE IF EXISTS history;

CREATE TABLE user (
	id INTEGER PRIMARY KEY AUTOINCREMENT,
	username TEXT UNIQUE NOT NULL,
	password TEXT NOT NULL
);

CREATE TABLE history (
	id INTEGER PRIMARY KEY AUTOINCREMENT,
	user_id INTEGER NOT NULL,
	
	query TEXT UNIQUE NOT NULL,
	last_access TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
	count INTEGER NOT NULL DEFAULT 1,

	FOREIGN KEY (user_id) REFERENCES user (id)
);